variable "prefix" {}
variable "location" {}
variable "pat" {}
variable "user" {}
variable "org" {}
variable "pool" {}
variable "subscription" {}
variable "devops_project_name" {}
variable "aks_cluster_name" {}
